# -*- coding: utf-8 -*-
"""image-resampling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rrTUutG_UB79rend22GhD6o8H9eMXHDT
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt

LL = cv2.imread('lion-art.jpg')
LLCon = cv2.cvtColor(LL, cv2.COLOR_BGR2RGB)
plt.imshow(LLCon)
plt.title('Original')

#blur before subsample
blur1 =cv2.medianBlur(LLCon,5)
time1 = cv2.pyrDown(blur1)

blur2 =cv2.medianBlur(time1,5)
time2 = cv2.pyrDown(blur2)

blur3 =cv2.medianBlur(time2,5)
time3 = cv2.pyrDown(blur3)

blur4 =cv2.medianBlur(time3,5)
time4 = cv2.pyrDown(blur4)

blur5 =cv2.medianBlur(time4,5)
time5 = cv2.pyrDown(blur5)

plt.subplot(121),plt.imshow(time1),plt.title('One')
plt.xticks([]), plt.yticks([])

plt.subplot(122),plt.imshow(time2),plt.title('Two')
plt.xticks([]), plt.yticks([])

plt.subplot(121),plt.imshow(time3),plt.title('Three')
plt.xticks([]), plt.yticks([])

plt.subplot(122),plt.imshow(time4),plt.title('Four')
plt.xticks([]), plt.yticks([])

plt.subplot(111),plt.imshow(time5),plt.title('Five')
plt.xticks([]), plt.yticks([])

smooth = cv2.bilateralFilter(LLCon,30,500,500)
Highpassfilter= LLCon - smooth
Highpassfilterreimg = cv2.resize(Highpassfilter,(1920,1088))
reconstructionTime5 = cv2.resize(time5,None, fx = 32, fy = 32, interpolation = cv2.INTER_CUBIC) #incress 32 time

sharppen = Highpassfilterreimg + reconstructionTime5

plt.imshow(time5),plt.title('downsampling 5 time')

plt.imshow(reconstructionTime5),plt.title('reconstruct')

plt.imshow(Highpassfilterreimg),plt.title('Highpass')

plt.imshow(sharppen),plt.title('reconstruct shappen')

plt.imshow(LLCon),plt.title('Original')
